Repository denny/ShinyCMS-ruby, pull requests merged in 2025-05, with the labels that each got.

#1952 Upgrade to Rails 8.0
  Gemfile
  Gemfile.lock
  bin/dev
  config/application.rb
  config/puma.rb
  docs/Features/MainApp/admin-features.md
  lib/generators/shiny/plugin/plugin_builder.rb
  lib/generators/shiny/plugin/plugin_generator.rb
  lib/generators/shiny/plugin/plugin_generator_base.rb
  plugins/ShinyAccess/shiny_access.gemspec
  plugins/ShinyBlog/shiny_blog.gemspec
  plugins/ShinyCMS/README.md
  plugins/ShinyCMS/app/controllers/shinycms/admin/consent_versions_controller.rb
  plugins/ShinyCMS/app/controllers/shinycms/admin/feature_flags_controller.rb
  plugins/ShinyCMS/app/controllers/shinycms/admin/users_controller.rb
  plugins/ShinyCMS/app/controllers/shinycms/comments_controller.rb
  plugins/ShinyCMS/shinycms.gemspec
  plugins/ShinyForms/shiny_forms.gemspec
  plugins/ShinyInserts/shiny_inserts.gemspec
  plugins/ShinyLists/shiny_lists.gemspec
  plugins/ShinyNews/shiny_news.gemspec
  plugins/ShinyNewsletters/shiny_newsletters.gemspec
  plugins/ShinyPages/shiny_pages.gemspec
  plugins/ShinyProfiles/shiny_profiles.gemspec
  plugins/ShinySEO/shiny_seo.gemspec
  plugins/ShinySearch/shiny_search.gemspec
  public/400.html
Labels: ruby, major

#1974 Update rack to fix potential DoS attack
  Gemfile
  Gemfile.lock
Labels: dependencies, security

#1975 Fixes #1111 (rubocop RSpec/DescribedClassModuleWrapping warnings)
  plugins/ShinyAccess/spec/helpers/shiny_access/main_site_helper_spec.rb
  plugins/ShinyAccess/spec/models/shiny_access/group_spec.rb
  plugins/ShinyAccess/spec/models/shiny_access/membership_spec.rb
  plugins/ShinyBlog/spec/jobs/shiny_blog/build_atom_feed_job_spec.rb
  plugins/ShinyBlog/spec/models/shiny_blog/post_spec.rb
  plugins/ShinyCMS/.rubocop_todo.yml
  plugins/ShinyForms/spec/mailers/shiny_forms/form_mailer_spec.rb
  plugins/ShinyForms/spec/models/shiny_forms/form_spec.rb
  plugins/ShinyInserts/spec/models/shiny_inserts/element_spec.rb
  plugins/ShinyLists/spec/helpers/shiny_lists/main_site_helper_spec.rb
  plugins/ShinyLists/spec/models/shiny_lists/list_spec.rb
  plugins/ShinyLists/spec/models/shiny_lists/subscription_spec.rb
  plugins/ShinyNews/spec/jobs/shiny_news/build_atom_feed_job_spec.rb
  plugins/ShinyNewsletters/spec/jobs/shiny_newsletters/send_to_list_spec.rb
  plugins/ShinyNewsletters/spec/jobs/shiny_newsletters/send_to_subscriber_spec.rb
  plugins/ShinyNewsletters/spec/models/shiny_newsletters/edition_element_spec.rb
  plugins/ShinyNewsletters/spec/models/shiny_newsletters/edition_spec.rb
  plugins/ShinyNewsletters/spec/models/shiny_newsletters/send_spec.rb
  plugins/ShinyNewsletters/spec/models/shiny_newsletters/template_element_spec.rb
  plugins/ShinyNewsletters/spec/models/shiny_newsletters/template_spec.rb
  plugins/ShinyPages/spec/models/shiny_pages/page_element_spec.rb
  plugins/ShinyPages/spec/models/shiny_pages/section_spec.rb
  plugins/ShinyPages/spec/models/shiny_pages/template_element_spec.rb
  plugins/ShinyPages/spec/models/shiny_pages/template_spec.rb
  plugins/ShinyProfiles/spec/models/shiny_profiles/link_spec.rb
  plugins/ShinyProfiles/spec/models/shiny_profiles/profile_spec.rb
Labels: refactoring, code quality
